package com.shield.antitheft

import android.content.Context
import android.graphics.*
import android.graphics.pdf.PdfDocument
import android.location.Location
import android.net.Uri
import android.os.Environment
import androidx.core.content.FileProvider
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.*

class PDFReport(private val context: Context) {
    
    fun generateTheftReport(
        photos: List<File>,
        location: Location?,
        reason: String,
        deviceInfo: String
    ): File {
        val pdf = PdfDocument()
        val pageInfo = PdfDocument.PageInfo.Builder(595, 842, 1).create()
        val page = pdf.startPage(pageInfo)
        val canvas = page.canvas
        
        val titlePaint = Paint().apply { color = android.graphics.Color.BLACK; textSize = 16f; typeface = Typeface.DEFAULT_BOLD }
        val headerPaint = Paint().apply { color = android.graphics.Color.BLACK; textSize = 12f; typeface = Typeface.DEFAULT_BOLD }
        val textPaint = Paint().apply { color = android.graphics.Color.DKGRAY; textSize = 10f }
        val redPaint = Paint().apply { color = android.graphics.Color.RED; textSize = 12f; typeface = Typeface.DEFAULT_BOLD }
        
        var y = 40f
        
        // Title
        canvas.drawText("ANTI-THEFT SHIELD REPORT", 40f, y, titlePaint); y += 24f
        canvas.drawText("═══════════════════════", 40f, y, textPaint); y += 16f
        
        // Incident header
        canvas.drawText("INCIDENT DETAILS", 40f, y, headerPaint); y += 16f
        canvas.drawText("Date: ${SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(Date())}", 40f, y, textPaint); y += 14f
        canvas.drawText("Trigger: $reason", 40f, y, redPaint); y += 14f
        
        // Location
        if (location != null) {
            canvas.drawText("LOCATION", 40f, y, headerPaint); y += 16f
            canvas.drawText("Coordinates: ${location.latitude}, ${location.longitude}", 40f, y, textPaint); y += 14f
            canvas.drawText("Accuracy: ${location.accuracy}m", 40f, y, textPaint); y += 14f
            canvas.drawText("Google Maps: https://maps.google.com/?q=${location.latitude},${location.longitude}", 40f, y, textPaint); y += 14f
        }
        
        // Device info
        canvas.drawText("DEVICE INFORMATION", 40f, y, headerPaint); y += 16f
        canvas.drawText(deviceInfo, 40f, y, textPaint); y += 14f
        
        // Evidence summary
        canvas.drawText("EVIDENCE COLLECTED", 40f, y, headerPaint); y += 16f
        canvas.drawText("Photos captured: ${photos.size}", 40f, y, textPaint); y += 14f
        photos.forEachIndexed { i, photo ->
            canvas.drawText("  Photo ${i+1}: ${photo.name} (${photo.length() / 1024}KB)", 40f, y, textPaint); y += 12f
        }
        
        // Footer
        y = 800f
        canvas.drawText("Generated by AntiTheft Shield", 40f, y, textPaint); y += 14f
        canvas.drawText("This report is admissible as evidence", 40f, y, textPaint)
        
        pdf.finishPage(page)
        
        val file = File(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS), 
            "Shield_Report_${SimpleDateFormat("yyyyMMdd_HHmmss").format(Date())}.pdf")
        pdf.writeTo(FileOutputStream(file))
        pdf.close()
        
        return file
    }
    
    fun shareToWhatsApp(pdfFile: File, message: String) {
        try {
            val uri = FileProvider.getUriForFile(context, "${context.packageName}.fileprovider", pdfFile)
            val intent = android.content.Intent(android.content.Intent.ACTION_SEND).apply {
                type = "application/pdf"
                putExtra(android.content.Intent.EXTRA_STREAM, uri)
                putExtra(android.content.Intent.EXTRA_TEXT, message)
                setPackage("com.whatsapp")
                addFlags(android.content.Intent.FLAG_GRANT_READ_URI_PERMISSION)
            }
            context.startActivity(intent)
        } catch (e: Exception) {
            // WhatsApp not installed, try general share
            shareGeneral(pdfFile, message)
        }
    }
    
    fun shareToEmail(pdfFile: File, subject: String, body: String) {
        try {
            val uri = FileProvider.getUriForFile(context, "${context.packageName}.fileprovider", pdfFile)
            val intent = android.content.Intent(android.content.Intent.ACTION_SEND).apply {
                type = "message/rfc822"
                putExtra(android.content.Intent.EXTRA_EMAIL, arrayOf("emergency@gmail.com"))
                putExtra(android.content.Intent.EXTRA_SUBJECT, subject)
                putExtra(android.content.Intent.EXTRA_TEXT, body)
                putExtra(android.content.Intent.EXTRA_STREAM, uri)
                addFlags(android.content.Intent.FLAG_GRANT_READ_URI_PERMISSION)
            }
            context.startActivity(android.content.Intent.createChooser(intent, "Send Report"))
        } catch (e: Exception) {
            e.printStackTrace()
        }
    }
    
    fun shareGeneral(pdfFile: File, message: String) {
        try {
            val uri = FileProvider.getUriForFile(context, "${context.packageName}.fileprovider", pdfFile)
            val intent = android.content.Intent(android.content.Intent.ACTION_SEND).apply {
                type = "application/pdf"
                putExtra(android.content.Intent.EXTRA_STREAM, uri)
                putExtra(android.content.Intent.EXTRA_TEXT, message)
                addFlags(android.content.Intent.FLAG_GRANT_READ_URI_PERMISSION)
            }
            context.startActivity(android.content.Intent.createChooser(intent, "Share Report"))
        } catch (e: Exception) {
            e.printStackTrace()
        }
    }
}
